### ISSUE TITLE
Vagrant

### ISSUE THREAD

**Issue by maggiemusa** [ITAM-DS/programming-for-data-science-2019#1]
Hola  Profesor,

Me está generando este error cuando meto la instrucción de vagrant up.

A qué se deberá??

Saludos

<img width="580" alt="Captura de Pantalla 2019-09-02 a la(s) 22 35 56" src="https://user-images.githubusercontent.com/51722731/64142692-ac5b4680-cdd2-11e9-8f88-97ba15f41c82.png">

**Comment by nanounanue** [comment]
ver #2
