### ISSUE TITLE
Vagrant

### ISSUE THREAD

**Issue by maggiemusa** [ITAM-DS/programming-for-data-science-2019#2]
Hola Profesor,

Le mando la pantalla del error que me sale.

Saludos y gracias

![image](https://user-images.githubusercontent.com/51722731/64300182-7c7e8100-cf41-11e9-9535-6f73500306cc.png)

**Comment by dvilla88** [comment]
Hola Maggie,

Una consulta, ¿Cuándo ejecutaste esta linea **vagrant box add generic/ubuntu1904** escribiste **4)**?

![imagen](https://user-images.githubusercontent.com/51724809/64308364-99757d00-cf5e-11e9-8fc2-7f05f929cdd4.png)

Saludos

Diego Villa






> Hola Profesor,
> 
> Le mando la pantalla del error que me sale.
> 
> Saludos y gracias
> 
> ![image](https://user-images.githubusercontent.com/51722731/64300182-7c7e8100-cf41-11e9-9535-6f73500306cc.png)

**Comment by maggiemusa** [comment]
Hola Diego!!!,

El problema al parecer era vagrant, lo volví a instalar y ya no me marcó ningún error. Lo que veo es esto:

[cid:e6078106-f978-4929-8795-5242621e1d99]

La detuve con vagrant halt, pero lo que no sé si esté del todo bien es que cuando quise prender la máquina virtual otra vez con vagrant up tuve que cambiar la ruta a donde está la carpeta de vagrant-ds y ya con eso me salió esto:

[cid:7a7180f4-459c-4a1b-a478-c67234dfc0e4]

Hoy que el profe pidió que levantaramos la máquina virtual poniendo vagrant up, cambiaste tu pwd?

Saludos y muchas muchas gracias por preguntar.

________________________________
De: Diego Villa <notifications@github.com>
Enviado: miércoles, 4 de septiembre de 2019 09:57 p. m.
Para: ITAM-DS/programming-for-data-science-2019 <programming-for-data-science-2019@noreply.github.com>
CC: maggiemusa <maggie_musa@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [ITAM-DS/programming-for-data-science-2019] Vagrant (#2)


Hola Maggie,

Una consulta, ¿Cuándo ejecutaste esta linea vagrant box add generic/ubuntu1904 escribiste 4)?

[imagen]<https://user-images.githubusercontent.com/51724809/64308364-99757d00-cf5e-11e9-8fc2-7f05f929cdd4.png>

Saludos

Diego Villa

Hola Profesor,

Le mando la pantalla del error que me sale.

Saludos y gracias

[image]<https://user-images.githubusercontent.com/51722731/64300182-7c7e8100-cf41-11e9-9535-6f73500306cc.png>

**Comment by maggiemusa** [comment]
![image](https://user-images.githubusercontent.com/51722731/64311191-cc247300-cf68-11e9-857e-d4bbd0f8b2b8.png)

![image](https://user-images.githubusercontent.com/51722731/64311219-e2323380-cf68-11e9-856e-95eb7d4560ad.png)

Ay creo que en el anterior no se veían las imagenes.
